name: cleanflutter
description: A new Flutter project with a demo of clean architecture.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

  path_provider: ^1.3.0

  mock_web_server: ^4.1.1

  mockito: "^4.1.1"

  http: ^0.12.0

  injector: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

